benchmark:
  name: reduce_scatter
  xprof_timing: true
  params:
    warmup_tries: 5
    num_runs: 20
    dtype: bfloat16
    mesh_shape: 16x4x2
  sweep:
    sharding_strategy: ["16x4x1", "16x4x2"]
    matrix_dim: [512, 1024, 2048]
