benchmark:
  name: gemm
  xprof_timing: true
  params:
    warmup_tries: 5
    num_runs: 20
    out_dtype: bfloat16
  cases:
    - in_dtype: bfloat16
      m: 8192
      k: 8192
      n: 8192
    - in_dtype: bfloat16
      m: 16384
      k: 16384
      n: 16384
    - in_dtype: float8_e4m3fn
      m: 8192
      k: 8192
      n: 8192
    - in_dtype: float8_e4m3fn
      m: 16384
      k: 16384
      n: 16384
