benchmark:
  name: hbm
  xprof_timing: true
  params:
    warmup_tries: 5
    num_runs: 20
    dtype: bfloat16
    op_type: copy
  sweep:
    size:
      start: 67108864
      end: 536870912
      multiplier: 2
