benchmarks:
- benchmark_name: "gemm_simple"
  trace_dir: "../microbenchmarks/gemm_simple"
  csv_path: "../microbenchmarks/gemm_simple"
  xlml_metrics_dir: "../microbenchmarks/gemm_simple"
  xla_dump_dir: "../microbenchmarks/gemm_simple/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 16384, k: 16384, n: 16384}
