benchmark:
  name: all_reduce
  xprof_timing: true
  params:
    warmup_tries: 5
    num_runs: 20
    dtype: bfloat16
    reduce_op: sum
    mesh_shape: 4x4x2
  sweep:
    sharding_strategy: ["4x4x1", "4x4x2"]
    matrix_dim: [65536, 131072, 262144]
