benchmark:
  name: all_to_all
  xprof_timing: true
  params:
    warmup_tries: 5
    num_runs: 20
    dtype: bfloat16
    mesh_shape: 8x4x2
  sweep:
    sharding_strategy: ["8x4x1", "8x4x2"]
    matrix_dim: [8192, 16384, 32768]
